---
 - hosts: all
   gather_facts: no

   vars_files: 
    - '../vars/password_mysql.yml'
    
   tasks:

   - name: 'ssh default config'
     template: 'src=../templates/ssh/sshd_config.j2 dest=/etc/ssh/sshd_config'
     notify:
     - 'ssh restart'

   - name: 'iptables default config'
     template: 'src=../templates/iptables/iptables.j2 dest=/root/iptables'

   - name: 'rc.local default config'
     template: 'src=../templates/iptables/rc.local.j2 dest=/etc/rc.local'

   - include: ../tasks/preparation.yml

   - name: 'installing mysql'
     apt: 'name=mysql-server'
     notify: 
      - 'mysql server install'
       
   - name: 'installing packages'
     action: 'apt name={{ item }} state=latest update_cache=yes'
     with_items: 
      - 'mc'
      - 'nginx'
      - 'php5-fpm'
      - 'php5-mcrypt'
      - 'php5-mysql'
      - 'php5-curl'
      - 'php-db'
      - 'php5-gd'
      - 'unzip'
      - 'zip'
      - 'htop'
      - 'sendmail'

   - name: 'nginx default host'
     template: 'src=../templates/nginx/default.j2 dest=/etc/nginx/sites-available/default'

   - name: 'php5 default config'
     template: 'src=../templates/php5/fpm/php.ini.j2 dest=/etc/php5/fpm/php.ini'

   - name: 'nginx default config'
     template: 'src=../templates/nginx/nginx.conf.j2 dest=/etc/nginx/nginx.conf'

   - name: 'nginx fastcgi_params'
     template: 'src=../templates/nginx/fastcgi_params.j2 dest=/etc/nginx/fastcgi_params'

   - name: 'add nginx host'
     template: 'src=../templates/nginx/site.conf.j2 dest=/etc/nginx/sites-available/site.conf'

   - name: 'link to nginx host'
     file: 'src=/etc/nginx/sites-available/site.conf dest=/etc/nginx/sites-enabled/site.conf state=link'
     notify:
     - 'nginx restart'

   - name: 'add php-fpm pool'
     template: 'src=../templates/php5/fpm/site.conf.j2 dest=/etc/php5/fpm/pool.d/site.conf'
     notify:
     - 'php-fpm restart'

   - name: 'timezone php-cli'
     replace: 'dest=/etc/php5/cli/php.ini regexp="^;date.timezone =$" replace="date.timezone = Europe/Moscow"'
      
   - name: 'create /var/www'   
     file: 'path=/var/www state=directory'

   - name: 'create /var/www/site'
     file: 'path=/var/www/site state=directory'

   - name: 'create /var/www/site/www'
     file: 'path=/var/www/site/www state=directory'

   - name: 'create /var/www/site/tmp'
     file: 'path=/var/www/site/tmp state=directory'

##################### Handlers #######################
   handlers:
   - name: 'ssh restart'
     service: 'name=ssh state=restarted'

   - name: 'nginx restart'
     service: 'name=nginx state=restarted'

   - name: 'mysql server install'
     command: 'mysqladmin -u root password {{ mysql_root_pass }}'

   - name: 'php-fpm restart'
     service: 'name=php5-fpm state=restarted'
